# Generated by Django 4.2.5 on 2023-10-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_tr', models.CharField(max_length=100)),
                ('descrip', models.TextField()),
                ('fecha_est', models.DateField()),
            ],
        ),
    ]
