# Generated by Django 4.2.5 on 2023-10-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppF', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('nombre', 'nombre_tr')},
        ),
        migrations.AddField(
            model_name='movie',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('nombre',)},
        ),
    ]
