# Generated by Django 4.2.5 on 2023-10-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppF', '0003_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='descrip',
            field=models.TextField(verbose_name='Descripción / Resumen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fecha_est',
            field=models.DateField(default='Day/Month/Year', verbose_name='Fecha de estreno'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Titulo de la pelicula'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='nombre_tr',
            field=models.CharField(max_length=100, verbose_name='Titulo (Traduccion)'),
        ),
    ]
