# Generated by Django 4.2.5 on 2023-10-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppF', '0005_alter_movie_fecha_est'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares', verbose_name='Imagen de avatar'),
        ),
    ]
